# Generated by Django 3.0.2 on 2020-03-31 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('desc', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('redirect_to', models.CharField(max_length=512)),
                ('unique', models.PositiveIntegerField(default=0)),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('non_campaign_unique', models.PositiveIntegerField(default=0)),
                ('non_campaign_sessions', models.PositiveIntegerField(default=0)),
                ('non_campaign_total', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique', models.PositiveIntegerField(default=0)),
                ('sessions', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world.Campaign')),
                ('redirect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world.Redirect')),
            ],
            options={
                'unique_together': {('redirect', 'campaign')},
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='redirects',
            field=models.ManyToManyField(related_name='campaigns', through='hello_world.CampaignCount', to='hello_world.Redirect'),
        ),
    ]
