version: "3.7"

networks:
    clicktrack:

services:
    clicktrack-db:
        image: postgres:12-alpine
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: clicktrack
            POSTGRES_DB: clicktrack
        volumes:
            - "./db:/var/lib/postgresql/data"
        networks:
            - clicktrack

    clicktrack-backend:
        build:
            context: ../..
            dockerfile: docker/development/Dockerfile
        volumes:
            - "../..:/app"
        ports:
            - "8000:8000"
        networks:
            - clicktrack
        depends_on:
            - clicktrack-db
        command: "/app/tools/run-development.sh"
