image: python:3.5.1

pipelines:
  default:
    - step:
        name: Build assets
        image: node:8.11.3
        caches:
          - node
        script:
          - npm install
          - npm run build
        artifacts:
          - clicktrack/static/**
          - webpack-stats.local.json
    - step:
        name: Run python tests
        caches:
          - pipenv
        script:
          - python -m venv env
          - cp clicktrack/settings/email.py.base clicktrack/settings/email.py
          - cp clicktrack/settings/db.py.base clicktrack/settings/db.py
          - env/bin/pip install -r requirements/local.txt
          - env/bin/pytest --junitxml ./test-reports/junit.xml
        services:
          - postgres
definitions:
  services:
    postgres:
      image: postgres
  caches:
    pipenv: env
